apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentenceservice
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sentenceservice
    spec:
      containers:
      - name: sentenceservice-pod
        image: jajabro/sentenceservice:latest
        ports:
        - containerPort: 8080