apiVersion: v1
kind: Service
metadata:
  name: sentenceservice
  labels:
    app: sentenceservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: sentenceservice
